# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-19 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=500)),
                ('Image', models.ImageField(upload_to='meal_image/')),
                ('Price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=500)),
                ('TotalPrice', models.IntegerField()),
                ('Status', models.IntegerField(choices=[(0, 'Created'), (1, 'Cooking'), (2, 'Ready'), (3, 'On the way'), (4, 'Delivered'), (5, 'Completed'), (6, 'Canceled')])),
                ('CreatedTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('PickedTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('SubTotalPrice', models.IntegerField()),
                ('Meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CookManagement.Meal')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='CookManagement.Order')),
            ],
        ),
    ]
