# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Identity', '0002_auto_20170621_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=500)),
                ('Logo', models.ImageField(upload_to='/Users/ericliang/workspace/FoodieService/media/meal_image/')),
                ('Price', models.IntegerField(default=0)),
                ('Cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Identity.Cook')),
            ],
        ),
    ]
