# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-19 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Identity', '0001_initial'),
        ('CookManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Cook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Identity.Cook'),
        ),
        migrations.AddField(
            model_name='order',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Identity.Customer'),
        ),
        migrations.AddField(
            model_name='meal',
            name='Cook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Identity.Cook'),
        ),
    ]
