# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Identity', '0003_auto_20170703_1929'),
        ('CookManagement', '0002_auto_20170627_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=500)),
                ('TotalPrice', models.IntegerField()),
                ('Status', models.IntegerField(choices=[(0, 'Created'), (1, 'Cooking'), (2, 'Ready'), (3, 'On the way'), (4, 'Delivered'), (5, 'Completed'), (6, 'Canceled')])),
                ('CreatedTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('PickedTime', models.DateTimeField(blank=True, null=True)),
                ('Cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Identity.Cook')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Identity.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('SubTotalPrice', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='meal',
            name='Image',
            field=models.ImageField(upload_to='meal_image/'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='Meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CookManagement.Meal'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CookManagement.Order'),
        ),
    ]
