# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=500)),
                ('Rating', models.CharField(max_length=500)),
                ('Tag', models.CharField(max_length=500)),
                ('Address', models.CharField(max_length=500)),
                ('Phone', models.CharField(max_length=500)),
                ('Logo', models.ImageField(upload_to='cook_logo/')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cook', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
