# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='Logo',
            field=models.ImageField(upload_to='/Users/ericliang/workspace/FoodieService/media/cook_logo/'),
        ),
    ]
