# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Identity', '0002_auto_20170621_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='Logo',
            field=models.ImageField(upload_to='cook_logo/'),
        ),
    ]
